
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `p_payment_app`;
CREATE TABLE `p_payment_bill` (
	id BIGINT (20) NOT NULL AUTO_INCREMENT,
	app_id varchar(50) NOT NULL COMMENT '应用ID',
	app_code varchar(100) NOT NULL COMMENT '应用秘钥',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	status varchar(50) NOT NULL DEFAULT 'PAY_PENDING' COMMENT '状态：ENABLED,DISABLED',
	note varchar(250) DEFAULT NULL COMMENT '备注',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `p_payment_bill`;
CREATE TABLE `p_payment_bill` (
	id BIGINT (20) NOT NULL AUTO_INCREMENT,
	payment_type varchar(50) DEFAULT NULL COMMENT '支付类型，WECHAT，ALIPAY',
	out_order_num varchar(100) NOT NULL COMMENT '业务系统的订单号',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	status varchar(50) NOT NULL DEFAULT 'PAY_PENDING' COMMENT '状态：PAY_PENDING,PAID,REFUNDED',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
